# Generated by Django 3.1.2 on 2020-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_animemodel_lovemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
