# Generated by Django 3.1.2 on 2020-12-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sportsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animemodel',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lovemodel',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='mangamodel',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='model_test',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sportsmodel',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='animemodel',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='lovemodel',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='mangamodel',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='model_test',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='sportsmodel',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
