# Generated by Django 3.1.2 on 2020-12-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201227_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lovemodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mangamodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_test',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sportsmodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
